apiVersion: kyverno.io/v1

kind: ClusterPolicy
metadata:
  name: hostport-verify
  annotations:
    policies.kyverno.io/subject:  Pods
    policies.kyverno.io/description: >-
      The usage of hostPort is forbidden
spec:
  background:              true
  validationFailureAction: audit
  failurePolicy:           Fail
  rules: 
  - name: hostport-verify
    match:
      resources:
        kinds: 
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    validate:
      message: "The usage of hostPort is forbidden"
      anyPattern:
      - spec:
        containers:
        - =(ports):
            - X(hostPort) 
      - spec:
        =(initContainers):
        - =(ports):
            - X(hostPort) 
            
