apiVersion: kyverno.io/v1

kind: ClusterPolicy
metadata:
  name: registry-verify
  annotations:
    policies.kyverno.io/subject:  Pods
    policies.kyverno.io/description: >-
      Image is not proper signed
spec:
  background:              true
  validationFailureAction: audit
  webhookTimeoutSeconds:   20
  failurePolicy:           Fail
  rules: 
  - name: registry-verify
    match:
      resources:
        kinds: 
        - Pod
        namespaces:
        - "kunden*"
    verifyImages:
    - image: "*"
      key: |-
        -----BEGIN PUBLIC KEY-----
        jadajadj
        -----END PUBLIC KEY-----
